-- INSERT INTO chat.users (LOGIN, PASS, USERNAME) 
-- VALUES ('TEST', 'TEST','TEST');



INSERT INTO `chat`.`chat`
(`CHAT_NAME`,
`DESCRIPTION`)
VALUES
('PUBLIC', 'SDFFGYH'
);


INSERT INTO `chat`.`message`
(`FK_MESSAGE_USER_LOGIN`,
`FK_MESSAGE_CHAT_NAME`,
`MESSAGE_TEXT`)
VALUES
('TEST',
'PUBLIC',
'HELLO');


ALTER TABLE `chat`.`users` 
ADD INDEX `INDEX_PASS` (`PASS` ASC);

ALTER TABLE `chat`.`users` 
ADD UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC);


ALTER TABLE `chat`.`message` 
ADD UNIQUE INDEX `FK_MESSAGE_USER_LOGIN_UNIQUE` (`FK_MESSAGE_USER_LOGIN` ASC);
