-- 4. Добавить поле (cost - стоимость) в таблицу Projects .

use homework_1;

 ALTER TABLE projects 
 	ADD PROJECT_COST INT(11) DEFAULT NULL
 	AFTER PROJECT_NAME;

UPDATE projects SET PROJECT_COST=50000 WHERE PROJECT_ID=1;
UPDATE projects SET PROJECT_COST=65000 WHERE PROJECT_ID=2;
UPDATE projects SET PROJECT_COST=20000 WHERE PROJECT_ID=3;
UPDATE projects SET PROJECT_COST=45000 WHERE PROJECT_ID=4;
UPDATE projects SET PROJECT_COST=105000 WHERE PROJECT_ID=5;
UPDATE projects SET PROJECT_COST=500 WHERE PROJECT_ID=6;

SELECT * FROM projects; 