-- Добавить поле зарплата в таблицу developer_project

use homework_1;
-- ALTER TABLE developer_project ADD SALARY INT(6) DEFAULT NULL;

UPDATE developer_project SET SALARY = 1000 WHERE DEVELOPER_ID = 1 AND PROJECT_ID = 1;  
UPDATE developer_project SET SALARY = 1100 WHERE DEVELOPER_ID = 7 AND PROJECT_ID = 1;  
UPDATE developer_project SET SALARY = 1300 WHERE DEVELOPER_ID = 3 AND PROJECT_ID = 2;  
UPDATE developer_project SET SALARY = 1400 WHERE DEVELOPER_ID = 3 AND PROJECT_ID = 3;  
UPDATE developer_project SET SALARY = 900 WHERE DEVELOPER_ID = 2 AND PROJECT_ID = 4;  
UPDATE developer_project SET SALARY = 850 WHERE DEVELOPER_ID = 5 AND PROJECT_ID = 4;  
UPDATE developer_project SET SALARY = 700 WHERE DEVELOPER_ID = 1 AND PROJECT_ID = 5;  
UPDATE developer_project SET SALARY = 1500 WHERE DEVELOPER_ID = 4 AND PROJECT_ID = 5;  
UPDATE developer_project SET SALARY = 1350 WHERE DEVELOPER_ID = 6 AND PROJECT_ID = 5;  
UPDATE developer_project SET SALARY = 1200 WHERE DEVELOPER_ID = 7 AND PROJECT_ID = 5;  
UPDATE developer_project SET SALARY = 1100 WHERE DEVELOPER_ID = 2 AND PROJECT_ID = 6;  
  
SELECT * FROM developer_project;